CREATE DATABASE BooksMaster;

USE BooksMaster;

CREATE TABLE Ganre 
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Author 
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	FirsName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	DateOfBirth DATE,
	DateOfDeath DATE,
	County VARCHAR(50)
)

CREATE TABLE Book 
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	Title VARCHAR(50) NOT NULL,
	Author_Id INT NOT NULL,
	ReleaseDate DATE,
	Ganre_Id INT,
	Status VARCHAR(50),
	Rating INT,
	FOREIGN KEY (Author_Id) REFERENCES Author (Id),
	FOREIGN KEY (Ganre_Id) REFERENCES Ganre (Id),
)

CREATE TABLE Collections 
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
	Name VARCHAR(50),
	Book_Id INT NOT NULL,
	FOREIGN KEY (Book_Id) REFERENCES Book (Id),
)