//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Collections = new HashSet<Collections>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int Author_Id { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> Ganre_Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Ganre Ganre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collections> Collections { get; set; }
    }
}
